- smoker/server/plugins/testconnection.py
also fixes SyntaxError on smoker build
> testconnection plugin: PEP8 compliance

- README.md
- bin/smokerd.py
- smoker/logger/__init__.py
Itnroduces ability to configure logging by a file in python's
logging.config format.
> file based logging configuration

- Makefile
- smoker.spec
Add the target for easier version bumping.
> make version target

- setup.py
- smoker.spec
Since 2.0-1 < 2.0-6.rc2, the previous stable version.
2.0.0-1 > 2.0-6.rc2.
> bump version to 2.0.1

- setup.py
- smoker.spec
- smoker/client/out_junit/__init__.py
- smoker/client/out_junit/default_config.py
and don't report warnings as failures
> junit: handle plugins without components

- setup.py
- smoker.spec
- smoker/server/daemon.py
- smoker/server/plugins/__init__.py
Introduces the possibility to specify number of concurrent
plugins in the config file.
> configurable plugin throttling

- setup.py
- smoker.spec
Handle initscript and example config files by specfile rather than
setuptools.
> out of package files handling

- setup.py
- smoker.spec
init script has to be executable
> initscript: fix permissions

- setup.py
- smoker.spec
- smoker/logger/__init__.py
when loading logger config from file
> don't disable existing loggers

- bin/check_smoker_plugin.py
> FEATURE: DSS-2594 improve usability of check_smoker_plugin

- setup.py
- smoker.spec
- smoker/client/cli.py
E.g. take warnings as ok rather than error.
> TRIVIAL: exit 0 with plugins in warning state

- smoker/server/restserver.py
Function 'next_run_iso_format' should return 'next_run'
server/restserver.py#L24
Function 'standardized_api_list' should check 'component' data type.
server/restserver.py#L34
> TRIVIAL: Fix various trivial bugs

- tests/server/test_plugins.py
Test: https://ci.intgdc.com/job/lhv-chhung-smoker-unittests/8/console
> BUGFIX: Run unittests with python2.6

- tests/server/smoker_test_resources/client_mock_result.py
- tests/server/test_client.py
- tests/server/test_plugins.py
Passed test on CI : https://ci.intgdc.com/job/lhv-chhung-smoker-unittests/10/console
> FUTURE: Add unit tests for client - Part 2

- README.md
- setup.py
- smoker.spec
- smoker/client/cli.py
- smoker/server/plugins/__init__.py
- tests/server/test_plugins.py
And revert previous maintenance lock feature.
> CODE: Filter plugins based on locked platform status

- bin/smokerd.py
- smoker.spec
- smokerd.service
* Provide systemd unit file on Red Hat 7+
* Handle services correctly on rpm upgrades
* Emulate monit supervisor using Restart=always
> FEATURE: PAAS-5928 Systemd unit file for smokerd

- smokerd.service
* We should have network and syslog up before starting smokerd
> TRIVIAL: Add missing systemd dependency links

- rc.d/init.d/smokerd
- setup.py
- smoker.spec
Get rid of lockfile and rely on pgrep.
> Simplify initscript

- README.md
Fix small typo in the README.md
> Fix small typo in the README.md

- py3_requirements.txt
- smoker.spec
Setuptools version should be at least 40.8.0 because solve PEP 517.
> PAAS-17323 Ensure setuptools version

- bin/check_smoker_plugin.py
- smoker.spec
Truncate component details currently longer than 256 chars.
Relates to #77
> WA-12252 - Truncate long component details

- py2_requirements.txt
- smoker.spec
- smoker/client/__init__.py
- smoker/client/out_junit/__init__.py
- smoker/util/progressbar.py
- tests/server/test_plugins.py
Signed-off-by: Igor Raits <igor.raits@gmail.com>
> TRIVIAL: Finish Python 3 support, fix/run tests and fix packaging

- bin/check_smoker_plugin.py
- smoker.spec
Signed-off-by: Igor Raits <igor.raits@gmail.com>
> PAAS-17589: Fixup check_smoker_plugin on python 2

- py3_requirements.txt
- smoker.spec
Signed-off-by: Igor Raits <igor.raits@gmail.com>
> TRIVIAL: Drop useless setuptools dependency

- bin/check_smoker_plugin.py
- smoker.spec
Signed-off-by: Igor Raits <igor.raits@gmail.com>
> TRIVIAL: More python3 fixes
